version: '3.8'

services:
  axonserver:
    image: axoniq/axonserver:latest-jdk-17-dev
    container_name: calculatorAxonServer
    environment:
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: "true"
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    volumes:
      - ./volumes/axonserver/data:/axonserver/data
      - ./volumes/axonserver/events:/axonserver/events
  mongodb:
    image: mongo:5
    container_name: calculatorMongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
